// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"interface/internal/consts"
	"interface/internal/model/entity"
	"interface/internal/service/internal/dao/internal"
)

// adminDao is the data access object for table s_admin.
// You can define custom methods on it to extend its functionality as you wish.
type adminDao struct {
	*internal.AdminDao
}

func (d adminDao) FindByUname(ctx context.Context, uname string) (*entity.Admin, error) {
	var data entity.Admin
	one, err := d.Ctx(ctx).One("uname", uname)
	if err != nil {
		return nil, err
	}
	if one.IsEmpty() {
		return nil, consts.ErrDataNotFound
	}
	if err = one.Struct(&data); err != nil {
		return nil, err
	}
	return &data, nil
}

var (
	// Admin is globally public accessible object for table s_admin operations.
	Admin = adminDao{
		internal.NewAdminDao(),
	}
)

// Fill with you ideas below.
