// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"interface/internal/model/entity"
	"interface/internal/service/internal/dao/internal"
)

// apiDao is the data access object for table s_api.
// You can define custom methods on it to extend its functionality as you wish.
type apiDao struct {
	*internal.ApiDao
}

func (d apiDao) Insert(ctx context.Context, data *entity.Api) error {
	_, err := d.Ctx(ctx).Insert(data)
	if err != nil {
		return err
	}
	return nil
}

func (d apiDao) Delete(id int) error {
	return nil
}

var (
	// Api is globally public accessible object for table s_api operations.
	Api = apiDao{
		internal.NewApiDao(),
	}
)

// Fill with you ideas below.
