// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// bookChapterDao is the data access object for table b_book_chapter.
// You can define custom methods on it to extend its functionality as you wish.
type bookChapterDao struct {
	*internal.BookChapterDao
}

var (
	// BookChapter is globally public accessible object for table b_book_chapter operations.
	BookChapter = bookChapterDao{
		internal.NewBookChapterDao(),
	}
)

// Fill with you ideas below.
