// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// bookContentDao is the data access object for table b_book_content.
// You can define custom methods on it to extend its functionality as you wish.
type bookContentDao struct {
	*internal.BookContentDao
}

var (
	// BookContent is globally public accessible object for table b_book_content operations.
	BookContent = bookContentDao{
		internal.NewBookContentDao(),
	}
)

// Fill with you ideas below.
