// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// iconDao is the data access object for table s_icon.
// You can define custom methods on it to extend its functionality as you wish.
type iconDao struct {
	*internal.IconDao
}

var (
	// Icon is globally public accessible object for table s_icon operations.
	Icon = iconDao{
		internal.NewIconDao(),
	}
)

// Fill with you ideas below.
