// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// loginLogDao is the data access object for table u_login_log.
// You can define custom methods on it to extend its functionality as you wish.
type loginLogDao struct {
	*internal.LoginLogDao
}

var (
	// LoginLog is globally public accessible object for table u_login_log operations.
	LoginLog = loginLogDao{
		internal.NewLoginLogDao(),
	}
)

// Fill with you ideas below.
