// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// roleApiDao is the data access object for table s_role_api.
// You can define custom methods on it to extend its functionality as you wish.
type roleApiDao struct {
	*internal.RoleApiDao
}

var (
	// RoleApi is globally public accessible object for table s_role_api operations.
	RoleApi = roleApiDao{
		internal.NewRoleApiDao(),
	}
)

// Fill with you ideas below.
