// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// timeHistoryDao is the data access object for table t_time_history.
// You can define custom methods on it to extend its functionality as you wish.
type timeHistoryDao struct {
	*internal.TimeHistoryDao
}

var (
	// TimeHistory is globally public accessible object for table t_time_history operations.
	TimeHistory = timeHistoryDao{
		internal.NewTimeHistoryDao(),
	}
)

// Fill with you ideas below.
