// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// userDetailsDao is the data access object for table u_user_details.
// You can define custom methods on it to extend its functionality as you wish.
type userDetailsDao struct {
	*internal.UserDetailsDao
}

var (
	// UserDetails is globally public accessible object for table u_user_details operations.
	UserDetails = userDetailsDao{
		internal.NewUserDetailsDao(),
	}
)

// Fill with you ideas below.
