// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/internal/service/internal/dao/internal"
)

// writerDao is the data access object for table b_writer.
// You can define custom methods on it to extend its functionality as you wish.
type writerDao struct {
	*internal.WriterDao
}

var (
	// Writer is globally public accessible object for table b_writer operations.
	Writer = writerDao{
		internal.NewWriterDao(),
	}
)

// Fill with you ideas below.
