// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BookChapter is the golang structure for table book_chapter.
type BookChapter struct {
	Id          uint64      `json:"id"          description:""`
	BookId      uint64      `json:"bookId"      description:""`
	Name        string      `json:"name"        description:""`
	HiddenWords string      `json:"hiddenWords" description:""`
	Sort        int         `json:"sort"        description:""`
	Type        int         `json:"type"        description:"1zh 2en"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
}
