// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Book is the golang structure for table book.
type Book struct {
	Id             uint64      `json:"id"             description:""`
	Tid            uint64      `json:"tid"            description:""`
	CategoryId     uint64      `json:"categoryId"     description:""`
	FirstChapterId uint64      `json:"firstChapterId" description:""`
	TypeDetails    int         `json:"typeDetails"    description:"- 小说             - 诗歌             - 散文             - 童话             - 传记"`
	WriterId       uint64      `json:"writerId"       description:""`
	Name           string      `json:"name"           description:""`
	Icon           string      `json:"icon"           description:""`
	HiddenWords    string      `json:"hiddenWords"    description:""`
	Summary        string      `json:"summary"        description:""`
	Sort           int         `json:"sort"           description:""`
	Scope          uint        `json:"scope"          description:""`
	Status         int         `json:"status"         description:"1 ok 2 off 3 home show"`
	Theme          string      `json:"theme"          description:"#96b97d,dark,#f6f4f0,dark  top:light top:dark nav:light nav:dark"`
	ClickNum       uint64      `json:"clickNum"       description:""`
	PublishTime    string      `json:"publishTime"    description:""`
	CreatedAt      *gtime.Time `json:"createdAt"      description:""`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:""`
	Ex1            string      `json:"ex1"            description:""`
}
