// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BookContent is the golang structure for table book_content.
type BookContent struct {
	Id        uint64      `json:"id"        description:""`
	ChapterId uint64      `json:"chapterId" description:""`
	Summary   string      `json:"summary"   description:""`
	Content   string      `json:"content"   description:""`
	Type      int         `json:"type"      description:"1文字 2链接"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
