// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-30 15:53:54
// =================================================================================

package entity

// RoleMenu is the golang structure for table role_menu.
type RoleMenu struct {
	Id  uint64 `json:"id"  description:""`
	Rid uint64 `json:"rid" description:""`
	Mid uint64 `json:"mid" description:""`
}
