// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package entity

// RoleApi is the golang structure for table role_api.
type RoleApi struct {
	Id  uint64 `json:"id"  description:""`
	Rid uint64 `json:"rid" description:""`
	Aid uint64 `json:"aid" description:""`
}
