// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TimeHistory is the golang structure for table time_history.
type TimeHistory struct {
	Id          uint64      `json:"id"          description:""`
	Century     int         `json:"century"     description:""`
	Year        int         `json:"year"        description:""`
	Month       int         `json:"month"       description:""`
	Day         int         `json:"day"         description:""`
	Type        int         `json:"type"        description:"1科学技术 2战争与政治 3天灾人祸 4疾病与医学 5环境与自然 6社会与经济() 7 文化娱乐(书籍记录) 8 宗教与哲学() 9人物与事件(记录人物) 10问题与解决 11other 12 category"`
	TypeDetails int         `json:"typeDetails" description:"1 things 2birthday 3 dead 4book publish"`
	Name        string      `json:"name"        description:""`
	Summary     string      `json:"summary"     description:""`
	Content     string      `json:"content"     description:""`
	Tag         string      `json:"tag"         description:""`
	Sort        float64     `json:"sort"        description:""`
	Status      int         `json:"status"      description:""`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
}
