// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Writer is the golang structure for table writer.
type Writer struct {
	Id        uint64      `json:"id"        description:""`
	Tid       uint64      `json:"tid"       description:""`
	Name      string      `json:"name"      description:""`
	Icon      string      `json:"icon"      description:""`
	Summary   string      `json:"summary"   description:""`
	Ex1       string      `json:"ex1"       description:""`
	Words     string      `json:"words"     description:""`
	Sort      int         `json:"sort"      description:""`
	Status    int         `json:"status"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
