// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/app/dao/internal"
)

// apiDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type apiDao struct {
	*internal.ApiDao
}

var (
	// Api is globally public accessible object for table s_api operations.
	Api apiDao
)

func init() {
	Api = apiDao{
		internal.NewApiDao(),
	}
}

// Fill with you ideas below.
