// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"interface/app/dao/internal"
)

// roleApiDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type roleApiDao struct {
	*internal.RoleApiDao
}

var (
	// RoleApi is globally public accessible object for table s_role_api operations.
	RoleApi roleApiDao
)

func init() {
	RoleApi = roleApiDao{
		internal.NewRoleApiDao(),
	}
}

// Fill with you ideas below.
