// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserDetailsDao is the data access object for table u_user_details.
type UserDetailsDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns UserDetailsColumns // columns contains all the column names of Table for convenient usage.
}

// UserDetailsColumns defines and stores column names for table u_user_details.
type UserDetailsColumns struct {
	Id        string //
	Uid       string //
	RealName  string //
	Desc      string //
	CreatedAt string //
	UpdatedAt string //
}

//  userDetailsColumns holds the columns for table u_user_details.
var userDetailsColumns = UserDetailsColumns{
	Id:        "id",
	Uid:       "uid",
	RealName:  "real_name",
	Desc:      "desc",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUserDetailsDao creates and returns a new DAO object for table data access.
func NewUserDetailsDao() *UserDetailsDao {
	return &UserDetailsDao{
		group:   "default",
		table:   "u_user_details",
		columns: userDetailsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserDetailsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserDetailsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserDetailsDao) Columns() UserDetailsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserDetailsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserDetailsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserDetailsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
