// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WriterDao is the data access object for table b_writer.
type WriterDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns WriterColumns // columns contains all the column names of Table for convenient usage.
}

// WriterColumns defines and stores column names for table b_writer.
type WriterColumns struct {
	Id        string //
	Tid       string //
	Name      string //
	Icon      string //
	Summary   string //
	Ex1       string //
	Words     string //
	Sort      string //
	Status    string //
	CreatedAt string //
	UpdatedAt string //
}

//  writerColumns holds the columns for table b_writer.
var writerColumns = WriterColumns{
	Id:        "id",
	Tid:       "tid",
	Name:      "name",
	Icon:      "icon",
	Summary:   "summary",
	Ex1:       "ex1",
	Words:     "words",
	Sort:      "sort",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewWriterDao creates and returns a new DAO object for table data access.
func NewWriterDao() *WriterDao {
	return &WriterDao{
		group:   "default",
		table:   "b_writer",
		columns: writerColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WriterDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WriterDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WriterDao) Columns() WriterColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WriterDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WriterDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WriterDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
