// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RoleMenuDao is the manager for logic model data accessing and custom defined data operations functions management.
type RoleMenuDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      roleMenuColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB          // DB is the raw underlying database management object.
	Table  string          // Table is the underlying table name of the DAO.
}

// RoleMenuColumns defines and stores column names for table s_role_menu.
type roleMenuColumns struct {
	Id  string //
	Rid string //
	Mid string //
}

// NewRoleMenuDao creates and returns a new DAO object for table data access.
func NewRoleMenuDao() *RoleMenuDao {
	columns := roleMenuColumns{
		Id:  "id",
		Rid: "rid",
		Mid: "mid",
	}
	return &RoleMenuDao{
		C:     columns,
		M:     g.DB("default").Model("s_role_menu").Safe(),
		DB:    g.DB("default"),
		Table: "s_role_menu",
	}
}
