// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type RoleDao struct {
	gmvc.M             // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      roleColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB      // DB is the raw underlying database management object.
	Table  string      // Table is the underlying table name of the DAO.
}

// RoleColumns defines and stores column names for table s_role.
type roleColumns struct {
	Id        string //
	Name      string //
	Status    string //
	CreatedAt string //
	UpdatedAt string //
}

// NewRoleDao creates and returns a new DAO object for table data access.
func NewRoleDao() *RoleDao {
	columns := roleColumns{
		Id:        "id",
		Name:      "name",
		Status:    "status",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
	}
	return &RoleDao{
		C:     columns,
		M:     g.DB("default").Model("s_role").Safe(),
		DB:    g.DB("default"),
		Table: "s_role",
	}
}
