// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Icon is the golang structure of table s_icon for DAO operations like Where/Data.
type Icon struct {
	g.Meta    `orm:"table:s_icon, dto:true"`
	Id        interface{} //
	Content   interface{} //
	Status    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
