// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// LoginLog is the golang structure of table u_login_log for DAO operations like Where/Data.
type LoginLog struct {
	g.Meta    `orm:"table:u_login_log, dto:true"`
	Id        interface{} //
	Uid       interface{} //
	Ip        interface{} //
	Desc      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
