// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Menu is the golang structure of table s_menu for DAO operations like Where/Data.
type Menu struct {
	g.Meta    `orm:"table:s_menu, dto:true"`
	Id        interface{} //
	Pid       interface{} //
	Name      interface{} //
	Path      interface{} //
	Icon      interface{} //
	Type      interface{} // 0 normal,1 group,2 divide
	Sort      interface{} //
	Status    interface{} // -1 off 1 ok
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
