// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// RoleApi is the golang structure of table s_role_api for DAO operations like Where/Data.
type RoleApi struct {
	g.Meta `orm:"table:s_role_api, dto:true"`
	Id     interface{} //
	Rid    interface{} //
	Aid    interface{} //
}
