// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// RoleMenu is the golang structure of table s_role_menu for DAO operations like Where/Data.
type RoleMenu struct {
	g.Meta `orm:"table:s_role_menu, dto:true"`
	Id     interface{} //
	Rid    interface{} //
	Mid    interface{} //
}
