// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserDetails is the golang structure of table u_user_details for DAO operations like Where/Data.
type UserDetails struct {
	g.Meta    `orm:"table:u_user_details, dto:true"`
	Id        interface{} //
	Uid       interface{} //
	RealName  interface{} //
	Desc      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
