// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// Admin is the golang structure for table s_admin.
type Admin struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	Rid       uint64      `orm:"rid"        json:"rid"`       //
	Uname     string      `orm:"uname"      json:"uname"`     //
	Icon      string      `orm:"icon"       json:"icon"`      //
	Pwd       string      `orm:"pwd"        json:"pwd"`       //
	Status    int         `orm:"status"     json:"status"`    //
	Desc      string      `orm:"desc"       json:"desc"`      //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}

// Api is the golang structure for table s_api.
type Api struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	Url       string      `orm:"url"        json:"url"`       //
	Method    string      `orm:"method"     json:"method"`    //
	Group     string      `orm:"group"      json:"group"`     //
	Desc      string      `orm:"desc"       json:"desc"`      //
	Status    int         `orm:"status"     json:"status"`    //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}

// Menu is the golang structure for table s_menu.
type Menu struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	Pid       uint64      `orm:"pid"        json:"pid"`       //
	Name      string      `orm:"name"       json:"name"`      //
	Path      string      `orm:"path"       json:"path"`      //
	Icon      string      `orm:"icon"       json:"icon"`      //
	Type      uint        `orm:"type"       json:"type"`      // 0 normal,1 group,2 divide
	Sort      float64     `orm:"sort"       json:"sort"`      //
	Status    int         `orm:"status"     json:"status"`    //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}

// Role is the golang structure for table s_role.
type Role struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	Name      string      `orm:"name"       json:"name"`      //
	Status    int         `orm:"status"     json:"status"`    //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}

// RoleApi is the golang structure for table s_role_api.
type RoleApi struct {
	Id  uint64 `orm:"id,primary" json:"id"`  //
	Rid uint64 `orm:"rid"        json:"rid"` //
	Aid uint64 `orm:"aid"        json:"aid"` //
}

// RoleMenu is the golang structure for table s_role_menu.
type RoleMenu struct {
	Id  uint64 `orm:"id,primary" json:"id"`  //
	Rid uint64 `orm:"rid"        json:"rid"` //
	Mid uint64 `orm:"mid"        json:"mid"` //
}

// Dict is the golang structure for table s_dict.
type Dict struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	K         string      `orm:"k"          json:"k"`         //
	V         string      `orm:"v"          json:"v"`         //
	Desc      string      `orm:"desc"       json:"desc"`      //
	Group     string      `orm:"group"      json:"group"`     //
	Status    int         `orm:"status"     json:"status"`    //
	Type      int         `orm:"type"       json:"type"`      // 0 文本，1 img
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}

// File is the golang structure for table s_file.
type File struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	Name      string      `orm:"name"       json:"name"`      //
	Group     string      `orm:"group"      json:"group"`     //
	Status    int         `orm:"status"     json:"status"`    //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}
