// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BookChapter is the golang structure of table b_book_chapter for DAO operations like Where/Data.
type BookChapter struct {
	g.Meta      `orm:"table:b_book_chapter, do:true"`
	Id          interface{} //
	BookId      interface{} //
	Name        interface{} //
	HiddenWords interface{} //
	Sort        interface{} //
	Type        interface{} // 1zh 2en
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
