// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BookContent is the golang structure of table b_book_content for DAO operations like Where/Data.
type BookContent struct {
	g.Meta    `orm:"table:b_book_content, do:true"`
	Id        interface{} //
	ChapterId interface{} //
	Summary   interface{} //
	Content   interface{} //
	Type      interface{} // 1文字 2链接
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
