// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BookCategory is the golang structure of table b_book_category for DAO operations like Where/Data.
type BookCategory struct {
	g.Meta      `orm:"table:b_book_category, do:true"`
	Id          interface{} //
	Name        interface{} //
	Icon        interface{} //
	Color       interface{} //
	HiddenWords interface{} //
	Type        interface{} // 1童话与儿童 2魔法与幻想 3战争与历史 4浪漫与爱情 5诗歌与艺术 6动作与冒险 7人物的故事 8动作与冒险 9神秘与侦探 10 科幻与宇宙 11惊悚与犯罪 12经济与理财 13时间的痕迹 14武器库 15问题与答案
	Sort        interface{} //
	Status      interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
