// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-30 15:53:54
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// RoleApi is the golang structure of table s_role_api for DAO operations like Where/Data.
type RoleApi struct {
	g.Meta `orm:"table:s_role_api, do:true"`
	Id     interface{} //
	Rid    interface{} //
	Aid    interface{} //
}
