// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TimeHistory is the golang structure of table t_time_history for DAO operations like Where/Data.
type TimeHistory struct {
	g.Meta      `orm:"table:t_time_history, do:true"`
	Id          interface{} //
	Century     interface{} //
	Year        interface{} //
	Month       interface{} //
	Day         interface{} //
	Type        interface{} // 1科学技术 2战争与政治 3天灾人祸 4疾病与医学 5环境与自然 6社会与经济() 7 文化娱乐(书籍记录) 8 宗教与哲学() 9人物与事件(记录人物) 10问题与解决 11other 12 category
	TypeDetails interface{} // 1 things 2birthday 3 dead 4book publish
	Name        interface{} //
	Summary     interface{} //
	Content     interface{} //
	Tag         interface{} //
	Sort        interface{} //
	Status      interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
