// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-27 15:11:39
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Writer is the golang structure of table b_writer for DAO operations like Where/Data.
type Writer struct {
	g.Meta    `orm:"table:b_writer, do:true"`
	Id        interface{} //
	Tid       interface{} //
	Name      interface{} //
	Icon      interface{} //
	Summary   interface{} //
	Ex1       interface{} //
	Words     interface{} //
	Sort      interface{} //
	Status    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
